speller_config:
  sentences_path: datasets/ru/small-sentences.txt.gz
  dict_path: datasets/ru/freq-dict.txt.gz
  min_word_freq: 1
  min_word_length: 2
  unigram_weight: 80
  bigram_weight: 100
  trigram_weight: 80
  auto_train_mode: false
