speller_config:
  sentences_path: ../datasets/bestContext/sentences.txt.gz
  dict_path: ../datasets/bestContext/freq-dict.txt.gz
  min_word_freq: 1
  min_word_length: 1
  unigram_weight: 3
  bigram_weight: 5
  trigram_weight: 2
  auto_train_mode: false
